version: '3'

services:
  app:
    image: qormoon/fiurinee_docker
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESSKEY: ${AWS_ACCESSKEY}
      AWS_SECRETKEY: ${AWS_SECRETKEY}
      AWS_BUCKET: ${AWS_BUCKET}
      hibernate_ddl_auto: update
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

